# Generated by Django 2.2.5 on 2020-05-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('vibration', models.IntegerField()),
                ('moisture', models.IntegerField()),
                ('gps_latitude', models.CharField(max_length=250)),
                ('gps_longitude', models.CharField(max_length=250)),
                ('gyro_x', models.FloatField()),
                ('gyro_y', models.FloatField()),
                ('gyro_z', models.FloatField()),
                ('accelero_x', models.FloatField()),
                ('accelero_y', models.FloatField()),
                ('accelero_z', models.FloatField()),
                ('displacement', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Node')),
            ],
        ),
    ]
