# Generated by Django 2.2.5 on 2020-03-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='node_device',
            new_name='node_id',
        ),
    ]
