# Generated by Django 2.2.5 on 2020-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
