# Generated by Django 2.2.5 on 2020-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200515_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='address',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
