# Generated by Django 2.2.5 on 2020-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20200526_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
