# Generated by Django 2.2.5 on 2020-06-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20200527_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='data',
            name='angular',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
