version: '3'

services:
    web:
        restart: always
        build: ./gmlews
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./gmlews/:/usr/src/gmlews/
        ports: 
            - "8000:8000"
        env_file: 
            - ./.env.dev
        depends_on: 
            - db
    db:
        restart: always
        image: postgres
        volumes:
            
